### ISSUE TITLE
Makefile?

### ISSUE THREAD

**Issue by paultanner** [omerk/pihwm#1]
Tried to make it and failed.  I'm not proficient with make or I'd fix it.
What I did: Just put the whole lot on my pi.  cd'd to pihwm and typed "make".
Using the recommend black raspberry distro and logged in as pi.
Paul

**Comment by omerk** [comment]
Hi Paul,

@jeremybennett recently did an overhaul of the build system and I will be merging his changes soon, I suggest you try his branch and let us know if it still fails to build.

Cheers,
Omer.

**Comment by paultanner** [comment]
Thx Omer,
I have his build and it runs.  I also have from 
him your workshop files that are not on your github.
Interestingly, we wired the 23008 differently.
Regards, Paul
At 10:20 AM 9/25/2012, you wrote:

> Hi Paul,
> 
> https://github.com/jeremybennett@jeremybennett 
> recently did an overhaul of the build system and 
> I will be merging his changes soon, I suggest 
> you try his branch and let us know if it still fails to build.
> 
> Cheers,
> Omer.
> 
> ­
> Reply to this email directly or 
> https://github.com/omerk/pihwm/issues/1#issuecomment-8848195view 
> it on GitHub.

Paul Tanner - Virtual Technologies - http://www.virtual-techno.com
Tel: +44 1494 581979 Mob: +44 7973 223239 mailto:paul@virtual-techno.com
